language: python
python: "3.6"
install:
  - pip install -r requirements.txt
  - pip install flake8
before_script:
  - flake8 .
env:
- TARGET=test
- TARGET=dist
script:
- if [ "$TARGET" == "test" ]; then python -m unittest -v; fi
- if [ "$TARGET" == "dist" ]; then pip install -r dev-requirements.txt && scripts/build.sh; fi
